### ISSUE TITLE
next.server.dynamicRoutes.map is a TypeError

### ISSUE THREAD

**Issue by Imlona** [kyle-mccarthy/nest-next#104]
**Describe the bug**
TypeError: Cannot read property 'map' of undefined
at Function.<anonymous> (/app/node_modules/nest-next/dist/render.module.js:38:60)

**Expected behavior**
nextServer.router.dynamicRoutes
nextServer.customRoutes.dynamicRoutes

**To Reproduce**

Repository URL: 

**Version**
- next.js: 12.1.5
- nest:
- nest-next: 10.1.0

**Comment by yakovlev-alexey** [comment]
Hi @gaoluona! Sorry for the delayed response. I've checked the test suite on next@12.1.5 and everything seems to be running fine.

Could you please also specify a few more things:
1) Whether you encounter this error in dev mode or in production?
2) What Node version are you using?
3) How do you provide `NextServer` instance to this package? 
4) Do you encounter this error when booting the application or when rendering a page?
5) Which pages/routes do you have in your application?

**Comment by Imlona** [comment]
http://www.yvk2x1.cn泪 ，这个是咱班棉花告诉我的，郧我试了试，挺好玩的，你也来吧，等你

**Comment by oustn** [comment]
> Hi @gaoluona! Sorry for the delayed response. I've checked the test suite on next@12.1.5 and everything seems to be running fine.
> 
> Could you please also specify a few more things:
> 
> 1. Whether you encounter this error in dev mode or in production?
> 2. What Node version are you using?
> 3. How do you provide `NextServer` instance to this package?
> 4. Do you encounter this error when booting the application or when rendering a page?
> 5. Which pages/routes do you have in your application?

next@13.2.1 emit the error

**Comment by manikant-yml** [comment]
Getting this error 
`Node` version - `v16.15.1`
`nest` version -` 9.0.0`
`next` version - `13.2.4`
`nest-next` version - `10.1.0`

_TypeError: Cannot read properties of undefined (reading 'map')
    at Function.<anonymous> (myproject\node_modules\nest-next\dist\render.module.js:38:60)
    at Generator.next (<anonymous>)
    at fulfilled (myproject\node_modules\nest-next\dist\render.module.js:14:58)_

**Comment by Imlona** [comment]
http://www.yvk2x1.cn泪 ，这个是咱班棉花告诉我的，郧我试了试，挺好玩的，你也来吧，等你

**Comment by xiaoyaozi1010** [comment]
@gaoluona I tried to upgrade `nest-next` and `next` to specific version and this issue has been resolved.
nest-next: ^9.6.0
next: 12.1.5

**Comment by Imlona** [comment]
http://www.yvk2x1.cn泪 ，这个是咱班棉花告诉我的，郧我试了试，挺好玩的，你也来吧，等你
