### ISSUE TITLE
Cannot read properties of undefined (reading 'nextConfig')

### ISSUE THREAD

**Issue by midnightcodr** [kyle-mccarthy/nest-next#107]
**Describe the bug**
Trying out nest-next with the most current versions
```
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "nest-next": "^10.1.0",
    "next": "^13.4.4",
```
With next@13.4.4 I am getting the following error and server is not able to start. Downgrading to a lower version such as 13.3.1 the problem went away.

- event compiled client and server successfully in 668 ms (158 modules)
- wait compiling...
[Nest] 98752  - 05/25/2023, 11:11:50 PM   ERROR [ExceptionHandler] Cannot read properties of undefined (reading 'nextConfig')
TypeError: Cannot read properties of undefined (reading 'nextConfig')
    at Function.<anonymous> (/path/to/project/node_modules/nest-next/dist/render.module.js:37:30)
    at Generator.next (<anonymous>)
    at fulfilled (/path/to/project/node_modules/nest-next/dist/render.module.js:14:58)

**Expected behavior**
Start nest server successfully

**Version**
- next.js:13.4.4
- nest:9.0.0
- nest-next: 10.1.0

**Comment by layunne** [comment]
i am having the same error. This was after next@13.4.3

**Comment by raychunghk** [comment]
To be more explicit, in the RenderModule, in next@13.4.2, it successfully passes NextServer to forRootAsync, but not after this version.
```
NextServer { options: { dev: true } }
```

**Comment by raychunghk** [comment]
I filed the issue to the next js repo issues
https://github.com/vercel/next.js/issues/51466

**Comment by kaminion** [comment]
> I filed the issue to the next js repo issues
> [vercel/next.js#51466](https://github.com/vercel/next.js/issues/51466)

So, It's going on.. it's not solved I saw that.

**Comment by Amantel** [comment]
Seems like a deal breaker to me
