### ISSUE TITLE
Facing error while running building production.

### ISSUE THREAD

**Issue by gaurav-bothra** [kyle-mccarthy/nest-next#63]
```
C:\Users\gaura\Desktop\basic>npm run start

> passthrough@1.0.0 start C:\Users\gaura\Desktop\basic
> cross-env NODE_ENV=production node .next/production-server/main.js

C:\Users\gaura\Desktop\basic\node_modules\next\dist\next-server\server\next-server.js:113
const filesystemUrls=this.getFilesystemPaths();const resolved=(0,_path.relative)(this.dir,untrustedFilePath);return filesystemUrls.has(resolved);}readBuildId(){const buildIdFile=(0,_path.join)(this.distDir,_constants.BUILD_ID_FILE);try{return _fs.default.readFileSync(buildIdFile,'utf8').trim();}catch(err){if(!_fs.default.existsSync(buildIdFile)){throw new Error(`Could not find a valid build in the '${this.distDir}' directory! Try building your app with 'next build' before starting the server.`);}throw err;}}get _isLikeServerless(){return(0,_config.isTargetLikeServerless)(this.nextConfig.target);}}exports.default=Server;function prepareServerlessUrl(req,query){const curUrl=(0,_url.parse)(req.url,true);req.url=(0,_url.format)({...curUrl,search:undefined,query:{...curUrl.query,...query}});}class NoFallbackError extends Error{}


Error: Could not find a valid build in the 'C:\Users\gaura\Desktop\basic\.next\.next' directory! Try building your app with 'next build' before starting the server.
    at Server.readBuildId (C:\Users\gaura\Desktop\basic\node_modules\next\dist\next-server\server\next-server.js:113:355)
    at new Server (C:\Users\gaura\Desktop\basic\node_modules\next\dist\next-server\server\next-server.js:3:120)
    at Object.createServer [as default] (C:\Users\gaura\Desktop\basic\node_modules\next\dist\server\next.js:2:638)
    at Object.<anonymous> (C:\Users\gaura\Desktop\basic\.next\production-server\application.module.js:34:65)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! passthrough@1.0.0 start: `cross-env NODE_ENV=production node .next/production-server/main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the passthrough@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gaura\AppData\Roaming\npm-cache\_logs\2020-10-01T07_55_08_781Z-debug.log
```

**Comment by kyle-mccarthy** [comment]
Can you verify that the app was built using `yarn build` or `npm run build` prior to running start?

**Comment by gaurav-bothra** [comment]
npm run build

**Comment by kyle-mccarthy** [comment]
Are you passing any options to next? It looks like it's trying to find the build in `...\basic\.next\.next`.
